version: '3'
services:
  frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8081
    ports:
      - 8080:8080
  backend:
    restart: always
    build: ./backend
    ports:
      - 8081:8081
    environment:
      - MONGO_URI=mongodb://mongo:27017/
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: